name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar el JDK en 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Ejeccutar las pruebas de TareaControllerTest
      - name: Run Tests for TareaController
        run: |
          mvn clean test -Dtest=TareaControllerTest

      # Paso 4: Construir el paquete
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Paso 5: Instalar Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | bash
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV

      # Paso 6: Desplegar en Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service 74f75348-a09e-4376-8125-d1ae91a2652a
